# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    vb.name = "docker"
  
    # Customize the amount of memory on the VM:
  end
  config.vm.define :docker do |docker|
    docker.vm.box = "bento/centos-8"
    docker.vm.network :forwarded_port, guest: 22, host: 8080
    docker.vm.network :private_network, ip: "192.168.33.25"
    docker.vm.provision "shell", :path => "provision_init.sh", :privileged => false
  end

end
